### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by hirokihara** [k-mopi/kihara.angular-todo#1]
ページを表示して、すぐ、テキストボックスが未入力の状態でaddボタンを押すと表題のエラーが発生する。

ページを表示して、一度でもtodoをaddしておけば、エラーとならない。

エラー全文
```
TypeError: Cannot read property 'text' of undefined
    at Scope.$scope.todoAdd (http://localhost:9000/scripts/main.js:8:43)
    at fn (eval at <anonymous> (http://localhost:9000/bower_components/angular/angular.js:12931:15), <anonymous>:2:212)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:9000/bower_components/angular/angular.js:22919:17)
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:15574:28)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:15673:23)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/bower_components/angular/angular.js:22924:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:9000/bower_components/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (http://localhost:9000/bower_components/jquery/dist/jquery.js:4121:28)
```

**Comment by hirokihara** [comment]
テキストボックスは`ng-model="todo.text"`としているが、未入力の状態でスコープ上で参照しようとすると、todo.textプロパティがundefined となってしまっている。

ngModelディレクティブの説明では、ngModelは、現スコープの式の評価によって与えられたプロパティを、紐付けようと試みます。 もし、プロパティがそのスコープ上にまだ存在しない場合は、暗黙的に作成され、スコープに追加されます。とあるが、うまく作成されていないような気がする。

**Comment by albatrosary** [comment]
コントローラーで初期化する必要があります。

```javascript
  $scope.todo = {
  	text: void 0
  };
```
全モジュールは次の通り
```javascript
var todoApp = angular.module('angular-todo', []);

todoApp.controller('TodoCtrl', function ($scope) {
  'use strict';
  $scope.todos = [];
  $scope.todo = {
  	text: void 0
  };

  $scope.todoAdd = function() {
    $scope.todos.push({'text': $scope.todo.text});
    console.log('add!!');
    $scope.todo = '';
  };

});
```

**Comment by hirokihara** [comment]
だいぶ勘違いしていた。このエラーはtextがundefinedだと言っているのではなく、undefinedの'text'プロパティを読み込む事ができないというエラーだった。。。

エラー全文
```
TypeError: Cannot read property 'text' of undefined
    at Scope.$scope.todoAdd (http://localhost:9000/scripts/main.js:8:43)
    at fn (eval at <anonymous> (http://localhost:9000/bower_components/angular/angular.js:12931:15), <anonymous>:2:212)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:9000/bower_components/angular/angular.js:22919:17)
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:15574:28)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:15673:23)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/bower_components/angular/angular.js:22924:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:9000/bower_components/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (http://localhost:9000/bower_components/jquery/dist/jquery.js:4121:28)
```
